name: reze-pharaoh
services:
  app:
    container_name: reze-pharaoh-bot
    image: ghcr.io/ighorpi/reze-pharaoh-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: '${DISCORD_TOKEN}'
      DISCORD_DEVELOPMENT_GUILD_ID: '${DISCORD_DEVELOPMENT_GUILD_ID}'
      DATABASE_URL: '${DATABASE_URL}'
